# Generated by Django 4.2 on 2025-04-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_critics_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
